Repository openedx/blockstore, pull requests merged in 2020-09, with the labels that each got.

#76 Update README to be more helpful
  README.rst
Labels: cc-reviewer, core committer, open edx community review, open-source-contribution

#70 [BD-6] OEP-18 compliance
  Makefile
  blockstore/apps/api/v1/views/bundles.py
  blockstore/apps/core/tests/test_models.py
  openedx.yaml
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/github.in
  requirements/local.in
  requirements/local.txt
  requirements/optional.txt
  requirements/pip-tools.in
  requirements/pip-tools.txt
  requirements/production.in
  requirements/production.txt
  requirements/test.in
  requirements/test.txt
Labels: blended, needs triage

#82 Upgrade blockstore to use Python 3.8 and Django 2.2+.
  .circleci/config.yml
  Dockerfile
  Dockerfile-dev
  Makefile
  README.rst
  blockstore/apps/api/urls.py
  blockstore/apps/api/v1/urls.py
  blockstore/apps/bundles/admin.py
  blockstore/apps/bundles/models.py
  blockstore/apps/bundles/tests/factories.py
  blockstore/apps/core/migrations/0002_auto_20200915_1203.py
  blockstore/settings/base.py
  blockstore/urls.py
  docker-compose-testserver.yml
  docker-compose.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/local.txt
  requirements/production.txt
  requirements/test.txt
  tagstore/backends/tagstore_django/models.py
  tagstore/tagstore_rest/urls.py
  tagstore/tagstore_rest/v1/urls.py
Labels: open-source-contribution, waiting on author

#86 [WIP] Revert "Revert "Upgrade blockstore to use Python 3.8 and Django 2.2+. (#82)""
  .circleci/config.yml
  Dockerfile-3.5
  Dockerfile-3.8
  Makefile
  README.rst
  blockstore/apps/api/urls.py
  blockstore/apps/api/v1/urls.py
  blockstore/apps/bundles/admin.py
  blockstore/apps/bundles/models.py
  blockstore/apps/bundles/tests/factories.py
  blockstore/apps/core/migrations/0002_auto_20200915_1203.py
  blockstore/settings/base.py
  blockstore/urls.py
  docker-compose-3.5.yml
  docker-compose-3.8.yml
  docker-compose-testserver-3.5.yml
  docker-compose-testserver-3.8.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/docs.txt
  requirements/local.txt
  requirements/production.txt
  requirements/test.txt
  tagstore/backends/tagstore_django/models.py
  tagstore/tagstore_rest/urls.py
  tagstore/tagstore_rest/v1/urls.py
Labels: cc-reviewer, open edx community review, open-source-contribution
