Repository openedx/blockstore, pull requests merged in 2021-09, with the labels that each got.

#121 Use django-enviro-2 instead of deprecated django-environ
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/local.txt
  requirements/production.txt
  requirements/test.txt
Labels: open-source-contribution, engineering review

#124 Switch to Github Actions and remove constraints on the `cryptography` and `mysqlclient` packages.
  .circleci/config.yml
  .github/workflows/ci.yml
  Dockerfile-3.8
  Makefile
  blockstore/urls.py
  docker-compose-3.8.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/local.txt
  requirements/production.txt
  requirements/test.txt
Labels: open-source-contribution, core committer, engineering review, cc-reviewer

#96 Remove tagstore.
  .coveragerc
  Makefile
  blockstore/apps/mysql_unicode/migrations/0001_initial.py
  blockstore/settings/base.py
  blockstore/templates/admin/tagstore_django/list_item.html
  blockstore/templates/admin/tagstore_django/tag_hierarchy.html
  blockstore/templates/admin/tagstore_django/taxonomy/change_form.html
  blockstore/urls.py
  decisions/0003-tagstore-removal.rst
  tagstore.json
  tagstore/README.rst
  tagstore/__init__.py
  tagstore/backends/__init__.py
  tagstore/backends/django.py
  tagstore/backends/tagstore_django/admin.py
  tagstore/backends/tagstore_django/migrations/0001_initial.py
  tagstore/backends/tagstore_django/migrations/0002_delete_all_app_models.py
  tagstore/backends/tagstore_django/models.py
  tagstore/backends/tagstore_django/templatetags/__init__.py
  tagstore/backends/tagstore_django/templatetags/tagstore_admin.py
  tagstore/backends/tests/__init__.py
  tagstore/constants.py
  tagstore/models/__init__.py
  tagstore/models/entity.py
  tagstore/models/taxonomy.py
  tagstore/models/user.py
  tagstore/mypy.ini
  tagstore/tagstore.py
  tagstore/tagstore_rest/__init__.py
  tagstore/tagstore_rest/routers.py
  tagstore/tagstore_rest/urls.py
  tagstore/tagstore_rest/v1/__init__.py
  tagstore/tagstore_rest/v1/serializers/__init__.py
  tagstore/tagstore_rest/v1/serializers/entities.py
  tagstore/tagstore_rest/v1/tests/__init__.py
  tagstore/tagstore_rest/v1/tests/test_serializers.py
  tagstore/tagstore_rest/v1/tests/test_views.py
  tagstore/tagstore_rest/v1/urls.py
  tagstore/tagstore_rest/v1/views/__init__.py
  tagstore/tagstore_rest/v1/views/entities.py
Labels: open-source-contribution, core committer, rejected
