Repository openedx/blockstore, pull requests merged in 2021-11, with the labels that each got.

#136 FAL-2522 Remove period from python version makefile var
  Dockerfile-38
  Makefile
  docker-compose-38.yml
  docker-compose-testserver-38.yml
Labels: open-source-contribution, waiting on author

#135 Make blockstore an installable package
  CHANGELOG.rst
  blockstore/__init__.py
  blockstore/api.py
  blockstore/apps/api/__init__.py
  blockstore/apps/api/apps.py
  blockstore/apps/api/exceptions.py
  blockstore/apps/api/methods.py
  blockstore/apps/api/models.py
  blockstore/apps/api/tests/__init__.py
  blockstore/apps/api/tests/test_blockstore_api.py
  blockstore/apps/bundles/apps.py
  blockstore/apps/bundles/migrations/0001_initial.py
  blockstore/apps/bundles/migrations/0002_create_drafts.py
  blockstore/apps/bundles/migrations/0003_update_character_set.py
  blockstore/apps/bundles/models.py
  blockstore/apps/mysql_unicode/migrations/0001_initial.py
  blockstore/apps/rest_api/__init__.py
  blockstore/apps/rest_api/constants.py
  blockstore/apps/rest_api/permissions.py
  blockstore/apps/rest_api/relations.py
  blockstore/apps/rest_api/routers.py
  blockstore/apps/rest_api/urls.py
  blockstore/apps/rest_api/v1/__init__.py
  blockstore/apps/rest_api/v1/serializers/__init__.py
  blockstore/apps/rest_api/v1/serializers/bundles.py
  blockstore/apps/rest_api/v1/serializers/collections.py
  blockstore/apps/rest_api/v1/serializers/drafts.py
  blockstore/apps/rest_api/v1/tests/__init__.py
  blockstore/apps/rest_api/v1/tests/helpers.py
  blockstore/apps/rest_api/v1/tests/test_authorization.py
  blockstore/apps/rest_api/v1/tests/test_contract.py
  blockstore/apps/rest_api/v1/urls.py
  blockstore/apps/rest_api/v1/views/__init__.py
  blockstore/apps/rest_api/v1/views/bundles.py
  blockstore/apps/rest_api/v1/views/collections.py
  blockstore/apps/rest_api/v1/views/drafts.py
  blockstore/settings/base.py
  blockstore/urls.py
  pycodestyle
  pylintrc
  pylintrc_tweaks
  setup.cfg
  setup.py
Labels: open-source-contribution, core committer, engineering review

#140 Make blockstore an installable package [SE-4987]
  CHANGELOG.rst
  blockstore/__init__.py
  blockstore/apps/api/__init__.py
  blockstore/apps/api/apps.py
  blockstore/apps/api/exceptions.py
  blockstore/apps/api/methods.py
  blockstore/apps/api/models.py
  blockstore/apps/api/tests/__init__.py
  blockstore/apps/api/tests/test_blockstore_api.py
  blockstore/apps/bundles/migrations/0003_update_character_set.py
  blockstore/apps/bundles/models.py
  blockstore/apps/mysql_unicode/migrations/0001_initial.py
  blockstore/apps/rest_api/__init__.py
  blockstore/apps/rest_api/constants.py
  blockstore/apps/rest_api/permissions.py
  blockstore/apps/rest_api/relations.py
  blockstore/apps/rest_api/routers.py
  blockstore/apps/rest_api/urls.py
  blockstore/apps/rest_api/v1/__init__.py
  blockstore/apps/rest_api/v1/serializers/__init__.py
  blockstore/apps/rest_api/v1/serializers/bundles.py
  blockstore/apps/rest_api/v1/serializers/collections.py
  blockstore/apps/rest_api/v1/serializers/drafts.py
  blockstore/apps/rest_api/v1/tests/__init__.py
  blockstore/apps/rest_api/v1/tests/helpers.py
  blockstore/apps/rest_api/v1/tests/test_authorization.py
  blockstore/apps/rest_api/v1/tests/test_contract.py
  blockstore/apps/rest_api/v1/urls.py
  blockstore/apps/rest_api/v1/views/__init__.py
  blockstore/apps/rest_api/v1/views/bundles.py
  blockstore/apps/rest_api/v1/views/collections.py
  blockstore/apps/rest_api/v1/views/drafts.py
  blockstore/settings/base.py
  blockstore/urls.py
  pycodestyle
  pylintrc
  pylintrc_tweaks
  setup.cfg
  setup.py
Labels: open-source-contribution, engineering code review
